### PR TITLE
Typescript conversion and Request context seperation

### PR DESCRIPTION
**Pull request by thomaspurchas**
This is quite a big change, so appreciate that this might be taking the library in a direction you want to go. I'm also happy to revert author modifications in `package.json`, I've only made those due to me using this fork in some projects already. Primary thing I've added here is proper request context separation using domains around requests, plus test to prove that it works.

The previous `useDomains` implementation didn't really do what it said on the tin, and wasn't using domains properly to achieve request separation. The only reason it sort of worked was due to some very specific implementation details within Hapi, which makes that approach extremely fragile.

Primary advantage of my approach is that it wraps the requests before they even enter Hapi, allow the use of all the `Sentry.*` functions like `Sentry.configureScope`, `Sentry.withScope`,`Sentry.captureException`, `Sentry.useUser` to "just work". No need to use the `request.sentryClient` object. You can just call `Sentry` directly from anywhere and know that your data will be correctly scoped to the current request.

This has some nice side effects like annotating errors that are thrown by Hapi itself, or any other plugin that might be manipulating the request as part of the lifecycle. It should also make it trivial to add complete performance tracing to this plugin, and bring it into complete feature parity with Express plugin that `@sentry/node` already provides.

I've also converted it to Typescript, I'm not sure how much value this provides, but it did catch a couple of bugs and will make it nicer to use the plugin within other Typescript projects.

This PR passes all the tests in the original version. I've made the minimum changes necessary to convert the tests to Typescript, so I'm hoping those tests prove backwards compatibility. Additionally add a single test based on the [`@sentry/node` Express request separation test](https://github.com/getsentry/sentry-javascript/blob/master/packages/node/test/manual/express-scope-separation/start.js) to prove request context separation.

With regards to the use of Domains and their status in NodeJS. The API is deprecated, but we have no choice but to use it until Sentry supports and alternative like [Async Hooks](https://nodejs.org/api/async_hooks.html). It's notable that the Domain API in Node was recently re-written to use Async Hooks, so it's clear the API isn't going anywhere soon.

I also know that there have been past concerns regarding the performance of Domains, I personally think it's an acceptable trade-off and Sentry seems to agree considering their usage of it. Additionally Sentry SDK guidance indicates that per-request context separation is an [expected feature](https://develop.sentry.dev/sdk/features/#scopes) in all Sentry SDKs, and I have admit, I personally found it very confusing when I didn't get request context separation out-of-the-box because the lack of request metadata on exceptions substantially reduces the value Sentry provides.

### CODE REVIEW

**Comment by fiws** [comment]
Wow! This is huge.  

I still need to review the code, and it will probably take quite some time, but the PR looks good at a first glance.

Just 2 things before i actually start looking into this:
* Do you know why the tests are failing here? (https://github.com/hydra-newmedia/hapi-sentry/pull/121/checks?check_run_id=3571581876)
* I saw that the TS conversion was done in separate commits and it was one of the last things. I think going TS could be the right choice for this library but do you think it's possible to split it of into a separate PR for easier reviewing?

**Comment by thomaspurchas** [comment]
Not sure why the tests are failing at the moment. I had them working locally so it might take a little while to figure out what's broken.

Happy to split this into two PRs, just give a few days to find the time.

**Comment by thomaspurchas** [comment]
@fiws PR #122 has the request separation without typescript work in it. I'll probably need to create a new PR for Typescript once #122 is merged, otherwise we'll have issues with Github diffs changing around a lot.

**Comment by fiws** [comment]
Thanks for splitting it up. This PR can be closed then right?

**Comment by thomaspurchas** [comment]
Yeah I think it can.

**Pull request closed without merging**
