### PR TITLE
Typescript conversion

### PR DESCRIPTION
**Pull request by thomaspurchas**
Rewrite the entire plugin using Typescript. This makes the plugin much easier to use in Typescript projects, and it also improves safety because intercepting requests etc is complex and tricky to reason about. Typescript helps to make sure we haven't made any serious mistakes.

### CODE REVIEW

**Comment by thomaspurchas** [comment]
@fiws typescript PR for after #122. Draft only because merging #122 will cause the diff to change substantially.

**Comment by fiws** [comment]
I'm sorry for the conflicts …

**Comment by lallenfrancisl** [comment]
Will this be merged ?

**Comment by rlam3** [comment]
Is this branch stale?

**Pull request closed without merging**
